### ISSUE TITLE
KMS Key Policy too broad

### ISSUE THREAD

**Issue by arjitj2** [masterpointio/terraform-aws-ssm-agent#10]
Hi there, according to everything I've read online, it's not a good thing to allow `*` AWS accounts to have access to the KMS key-- the default is `root` of the current AWS account.

https://github.com/masterpointio/terraform-aws-ssm-agent/blob/master/main.tf#L175

<img width="977" alt="image" src="https://user-images.githubusercontent.com/15092149/158632074-8e575ccb-7c8c-4406-b059-b676483dd34b.png">

**Comment by Gowiem** [comment]
@gberenice if you get the chance as part of your current PR, it might be worth to address this.
