### ISSUE TITLE
Permit IPv6 egress

### ISSUE THREAD

**Issue by mheffner** [masterpointio/terraform-aws-ssm-agent#21]
The security group [permits](https://github.com/masterpointio/terraform-aws-ssm-agent/blob/9adca81bc139c47187ba03360c05b80d850bca7f/main.tf#L129C11-L136) IPv4 egress, but does not permit IPv6. It would be great to support both!

**Comment by Gowiem** [comment]
@mheffner 100% and should be an easy thing to do. Feel free to submit a PR and we'll get it in ASAP or we'll leave this open and someone from my team will take a crack at it soon. We have a new engineer starting this week, so I may have him knock this out since it's simple and a good intro to the open source work we do internally.

**Comment by mheffner** [comment]
Thanks @Gowiem ! For now we've attached a second SG to the instances (we're using the tailscale module), so we're not in a big rush. No rush from our side, but I wanted to note the gap. Sounds like a great first ticket!

**Comment by Gowiem** [comment]
@mheffner my colleague @oycyc completed this work and [it has been released as 1.1.0](https://github.com/masterpointio/terraform-aws-ssm-agent/releases/tag/1.1.0). Let us know how it works for you!

**Comment by mheffner** [comment]
Thanks @Gowiem and @oycyc , any chance you can bump the dep in https://github.com/masterpointio/terraform-aws-tailscale?

**Comment by oycyc** [comment]
> Thanks @Gowiem and @oycyc , any chance you can bump the dep in https://github.com/masterpointio/terraform-aws-tailscale?

Great point, thanks for that!

**Comment by Gowiem** [comment]
@mheffner updated downstream in https://github.com/masterpointio/terraform-aws-tailscale/releases/tag/1.1.0 👍 Thanks for the push!

**Comment by mheffner** [comment]
Thanks  @oycyc !
