### ISSUE TITLE
Upgrade to AL 2023

### ISSUE THREAD

**Issue by mheffner** [masterpointio/terraform-aws-ssm-agent#23]
Hey @Gowiem , we discovered another IPv6 issue where the AL 2 images used in the tailscale module didn't seem to route IPv6 traffic by default. Tailscale also did not register IPv6 connectivity for the subnet router machines.

From the image this failed with a "network unreachable" error:
```
ping6 ipv6.google.com
```

We explicitly set the `ami` override to an Amazon Linux 2023 image and it seems to have fixed the issue for us. I don't know if you have a requirement for AL2, but AL2023 seems to be a bit better in this regard. Cheers!

**Comment by Gowiem** [comment]
No reason to stay on AL2. We'll upgrade. 

@oycyc assigning this your way again 😁

**Comment by mheffner** [comment]
Possibly related, but I noticed when we used this launch template that the GP3 volume was not marked as encrypted. I think that may be defined in the launch template?

**Comment by oycyc** [comment]
> Possibly related, but I noticed when we used this launch template that the GP3 volume was not marked as encrypted. I think that may be defined in the launch template?

Seems like both when we use AL2 (default GP2 volume) or or when we use AL3 (default GP3 volume):
<img width="811" alt="image" src="https://github.com/masterpointio/terraform-aws-ssm-agent/assets/35899715/d130bfa1-1d6b-438c-b721-d58a440da892">
<img width="760" alt="image" src="https://github.com/masterpointio/terraform-aws-ssm-agent/assets/35899715/c2b02a67-5338-4b7c-a3e0-a90838835d57">

I can specify the launch template for the volume to be encrypted. AFAIK there is no downside, @Gowiem is there anything that wouldn't make it a good idea to mark as encrypted by default?

**Comment by Gowiem** [comment]
@oycyc encryption by default is always good, go for it 👍
