### ISSUE TITLE
ARM64 v.s. x86_64

### ISSUE THREAD

**Issue by benhowes** [masterpointio/terraform-aws-ssm-agent#25]
By default this module selects [`t4g.nano`](https://github.com/masterpointio/terraform-aws-ssm-agent/blob/5b6d9947bbffb2a9ced75186a6059fbe62208e67/variables.tf#L22) as the instance type which is arm64 based, but [in `data.tf`](https://github.com/masterpointio/terraform-aws-ssm-agent/blob/5b6d9947bbffb2a9ced75186a6059fbe62208e67/data.tf#L16), the filtering is based on x86 only which is causing an error when applying since (naturally) an x86 machine image does not run on arm64 machines. 

I don't know if there's some easy way to fix this, but I thought I'd mention it since the defaults seem to be broken at the moment?

The error I see is:

```
api error ValidationError: You must use a valid fully-formed launch template. The architecture 'arm64' of the specified instance type does not match the architecture 'x86_64' of the specified AMI. Specify an instance type and an AMI that have matching architectures, and try again. You can use 'describe-instance-types' or 'describe-images' to discover the architecture of the instance type or AMI."
```

**Comment by gberenice** [comment]
Thanks for reporting this @benhowes! We'll take a look.

**Comment by oycyc** [comment]
Hey @benhowes, thanks again for bringing this up. Just changed the default of the instance to be compatible as of this release and added some validation + tests to the inputs so it's less likely for human input error! https://github.com/masterpointio/terraform-aws-ssm-agent/releases/tag/1.2.1
